branches:
  - +([0-9])?(.{+([0-9]),x).x}
  - master
  - name: next
    prerelease: rc

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/github"
    - assets:
        -  path: app/build/outputs/apk/app-debug.apk
  # commit changelog and push "release commit"
  - "@semantic-release/git"
